### ISSUE TITLE
problems with  installation

### ISSUE THREAD

**Issue by tboy-hacker** [k1nd0ne/VolWeb#18]
pls if you dont mind can you make a installation video or one script bash file

**Comment by k1nd0ne** [comment]
Hello, 

No installation videos or scripted bash file are on the roadmap right now. However, a first start page is currently under reflexion to better guide the user into the configuration on the S3 default storage solution. 

The documentation can be found [here](https://github.com/k1nd0ne/VolWeb/wiki/VolWeb-Documentation) in order to fully understand how the project works before deploying it.

Best regards.
